### ISSUE TITLE
Both the guidebook and Julia Silge's videos on glmnet lack a method for (creating a new column of) predicted values using elastic net

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/TMwR#160]
References (same page, different sections): https://www.tmwr.org/models.html#create-a-model and https://www.tmwr.org/models.html#use-the-model-results

In situations when elastic net or `glmnet` is used instead of linear regression, this guide doesn't really work. Here is what the guide says (copy/pasted):
```
lm_form_fit
#> parsnip model object
#> 
#> Fit time:  4ms 
#> 
#> Call:
#> stats::lm(formula = Sale_Price ~ Longitude + Latitude, data = data)
#> 
#> Coefficients:
#> (Intercept)    Longitude     Latitude  
#>     -300.25        -2.01         2.78
```
When in fact, `glmnet` output will look something more like this:
```
Call:  glmnet::glmnet(x = maybe_matrix(x), y = y, family = "gaussian",      alpha = ~0.5) 

   Df  %Dev Lambda
1   0  0.00 727400
2   1  0.99 662800
3   2  1.88 603900
4   2  2.68 550300
5   2  3.36 501400
6   2  3.94 456900
...
```
where generally, it would be more than 50 more rows of output. For elastic net from `glmnet`, what the guide's code needs is `tidy()`, taken from Julia Silge's video [here](https://www.youtube.com/watch?v=R32AsuKICAY).

However, using `predict()` for `glmnet` throws the error:
```
Error in predict.glmnet(spec_enet1_fit, new_data = df_test_small) : 
You need to supply a value for 'newx'
```

Both the guidebook and Julia Silge's video lack a method for creating a new column of predicted values using elastic net, as well as creating a graph for them (though I think that's going to be a lot easier).

**Comment by juliasilge** [comment]
I'm not sure why you are getting an error for prediction; I believe you should see something like this:

---
author: juliasilge
date: 2021-06-18
output: "reprex::reprex\\_document"
title: ok-coqui\_reprex.R
---

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
data(bivariate)

biv_rec <- 
  recipe(Class ~ ., data = bivariate_train) %>%
  step_BoxCox(all_predictors())%>%
  step_normalize(all_predictors())

glmnet_spec <-
  logistic_reg(penalty = 0.1, mixture = 0.5) %>%
  set_engine("glmnet")

biv_fit <- workflow() %>%
  add_recipe(biv_rec) %>%
  add_model(glmnet_spec) %>%
  fit(bivariate_train)

predict(biv_fit, bivariate_test, type = "prob")
#> # A tibble: 710 x 2
#>    .pred_One .pred_Two
#>        <dbl>     <dbl>
#>  1     0.648     0.352
#>  2     0.534     0.466
#>  3     0.667     0.333
#>  4     0.634     0.366
#>  5     0.574     0.426
#>  6     0.697     0.303
#>  7     0.561     0.439
#>  8     0.576     0.424
#>  9     0.618     0.382
#> 10     0.720     0.280
#> # … with 700 more rows
```

<sup>Created on 2021-06-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) showing how you see that error? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌
