### ISSUE TITLE
Any working examples of using `recipes` with reactive `Shiny`?

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/TMwR#177]
Since this is a recent development, it is very difficult to find resources on this. Reactive programming through Shiny adds another layer to using `recipes` and having a lot of difficulties. If not including in the book, even an external link of a working example would be greatly appreciated as a reference.

**Comment by juliasilge** [comment]
I've seen a couple of issues you've opened and I think mostly closed on this problem. People have definitely built Shiny apps based on tidymodels trained models (like put in new data and get a prediction back) but it sounds like that is not what you are trying to do.

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it, and in this case I suggest focusing on creating a truly minimal reprex so we can understand the problem you are running into.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by PathosEthosLogos** [comment]
Thanks for your reply.
I just created a reprex and it ran successfully by compartmentalising preprocessing steps, recipes, resampling, and plotting objectives into individual reactive objects. Before, I had them all combined into one process on the server side of Shiny, and I guess that doesn't work for some reason.
Closing the ticket for now.
