### ISSUE TITLE
black and white versions

### ISSUE THREAD

**Issue by topepo** [tidymodels/TMwR#212]
The resampling diagrams in chapter 10 need to have different colors. For example, there should be three distinct colors here: 

![image](https://user-images.githubusercontent.com/5731043/148664676-e5bdde8e-22b8-4428-87bc-b8ef84190765.png)

(or perhaps use shapes). 

The Ames map is also poor in monochrome. Perhaps use `ggrepl` to point to neighborhoods would work.

**Comment by juliasilge** [comment]
The top panel in Fig 1.1 needs some help:
![Screen Shot 2022-02-03 at 1 36 54 PM](https://user-images.githubusercontent.com/12505835/152424673-a731f729-0eb9-4c4c-a528-61119bc336ee.png)

**Comment by juliasilge** [comment]
Related, in #129 we need to fix one of the resampling diagrams

**Comment by juliasilge** [comment]
Many of the tuning `autoplot()` results don't make much sense visually without color:
![Screen Shot 2022-02-03 at 1 54 29 PM](https://user-images.githubusercontent.com/12505835/152427099-0230f238-e088-46aa-adf8-d0f8ec91c811.png)

What do want to know? One option would be to overload `autoplot` in `_common.R` and add `lty` (as well as make the points larger in general, because it's hard to see the shapes at their default size).

**Comment by juliasilge** [comment]
Another `autoplot` to possibly overload:
![Screen Shot 2022-02-03 at 1 57 29 PM](https://user-images.githubusercontent.com/12505835/152427495-8081bd37-4fa9-4f5f-99e9-63243e4f4e73.png)

**Comment by juliasilge** [comment]
@topepo If you can look at the images outlined in this issue, that would be great.
