### ISSUE TITLE
chapter 11. the effect of the amount of resampling code fail to run

### ISSUE THREAD

**Issue by ChandlerBBT** [tidymodels/TMwR#297]
## The problem

I'm having trouble with processing below code, seems the author didn't point out what data feeds into ggplot function.

## Reproducible example

```{r compare-cred-int, eval = FALSE}
# calculations in extras/ames_posterior_intervals.R
ggplot(intervals,
       aes(x = resamples, y = mean)) +
  geom_path() +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "red", alpha = .1) +
  labs(x = "Number of Resamples (repeated 10-fold cross-validation)")
```

Error message returned:

Error in ggplot(intervals, aes(x = resample, y = mean)) : 
  object 'intervals' not found

**Comment by juliasilge** [comment]
The comment points out where you can find the code to generate the intervals: <https://github.com/tidymodels/TMwR/blob/main/extras/ames_posterior_intervals.R>

It might be a good idea to put the full URL, especially for the printed book. What do you think @topepo? Maybe a footnote also, instead of the comment?
