### ISSUE TITLE
Figure 9.1 looks confusing

### ISSUE THREAD

**Issue by thrkng** [tidymodels/TMwR#366]
Figure 9.1 and the relating descriptions seem to claim that minimizing RMSE and maximizing coefficient of determination (R-squared) are different and lead to different predictions, which is confusing to me. 
I suppose R-squared is defined as $R^2 = 1 – \frac{\Sigma_{i=1}^{n}(y_i - \hat{y_i})^2}{\Sigma_{i=1}^{n}{(y_i – \bar{y})^2}}$ and that reduces to $R^2 = 1 – \frac{n \cdot {RMSE}^2}{\Sigma_{i=1}^{n}{(y_i – \bar{y})^2}}$.
Because $y_i$ and $\bar{y}$ do not change for the same dataset, minimizing RMSE should be equivalent to maximizing $R^2$.
Have I misunderstood anything...? (maybe coefficient of determination defined differently?) 

And I suppose RMSE and MAE (Mean Absolute Error) would be one of the candidates of sets of metrics that would clearly lead to different predictions.
Thank you for the great guide anyways.

**Comment by topepo** [comment]
> minimizing RMSE should be equivalent to maximizing $R^2$.

That's not always the case. $R^2$ measures correlation ($R$), not accuracy. You can have a tight correlation between the observed and predicted values but with an intercept that is not zero. This would give you a good $R^2$ but poor RMSE since some of the errors are large. 

In practice, this can happen with tree ensembles that have shallow trees. 

$R^2$ is normalized to a fraction by the total sums of squares and that makes it a _relative_ measure; RMSE is an _absolute_ measure of performance.

**Comment by thrkng** [comment]
Thank you for the reply.
According to [wikipedia](https://en.wikipedia.org/wiki/Coefficient_of_determination) and other sources, $R^2$ defined as the equation I wrote above equals to the square of correlation between the observed and predicted under certain limited conditions.
So to be clear, $R^2$ here is defined as the square of correlation between the observed and predicted, but not necessarily $1-\frac{\sum(y_i - \hat{y_i})^2}{\sum(y_i - \bar{y_i})^2}$, correct?

**Comment by topepo** [comment]
> $R^2$ defined as the equation 

Sorry to be picky, but that is not the case. The coefficient of determination _parameter_ is defined to be the proportion of the variation in the dependent variable that is predictable from the independent variable(s). 

The equation you show is an _estimator_ of $R^2$ derived from linear regression models. They are different estimators (and see [Kvalseth (1985)](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C7&q=kv%C3%A5lseth+1985+cautionary+note&oq=Kvalseth+1985) for even more). 

We tend to use the squared estimate of the estimate correlation because 1) it is not tied to linear models and 2) it works better when the estimate is near zero.

**Comment by thrkng** [comment]
Thank you for the clarification. That gave me an understanding of multiple $R^2$'s.
And now I found [rsq() in yardstick package](https://yardstick.tidymodels.org/reference/rsq.html) is explained to be "simply the squared correlation between truth and estimate", just as you told me.
I really appreciate your kind help and of course the great books and packages!
