### ISSUE TITLE
Code Broken Ch 10

### ISSUE THREAD

**Issue by biscotty666** [tidymodels/TMwR#374]
In 10.1, `estimate_perf(lm_fit, ames_train)` fails with 

```
! Can't subset columns that don't exist.
✖ Columns `Gr_Liv_Area`, `Bldg_Type_TwoFmCon`, `Bldg_Type_Duplex`, `Bldg_Type_Twnhs`, and `Bldg_Type_TwnhsE` don't exist.
```

Running the code in 8.8 solves the problem.

Thank you for the wonderful book.

**Comment by davidrsch** [comment]
It doesn't fail per se, because as stated previously to the example:

"Let’s again use the Ames housing data to demonstrate these concepts. Section 8.8 summarizes the current state of our Ames analysis."

It is using the data resulting from Section 8.8.

And when rendering the chapter, it's ensure that this data will be available in the source code when calling

 ```{r}
source("ames_snippets.R")
load("RData/lm_fit.RData")
```

**Comment by biscotty666** [comment]
I'm so grateful that you provide this for free. It's really top-notch.

⁣Get BlueMail for Android ​
