### ISSUE TITLE
Include compiled PDF in repo?

### ISSUE THREAD

**Issue by MaciekChudek** [tidymodels/TMwR#90]
I was keen to read the book in PDF format. To achieve this I had to:

1. Clone the git repo
2. Install necessary packages in R (...wait patiently for packages to compile or fail...)
3. Figure out why the package compilation failed, figure out which dependencies are missing, figure out how they're packaged for my distro, install them
4. Repeat step 2 (wait patiently...) and 3 until no more errors
5. Compile to PDF with bookdown
6. Find latex compilation errors, track down in .Rmd source files, fix (see my other issue for details)
7. Repeat step 5 and 6 till no more errors

I'd have been grateful if either the website or github repo had simply had a copy of the compiled PDF for easy download. Is this a possibility?

To help facilitate this, I've attached a copy of the compiled file.

[_main.pdf](https://github.com/tidymodels/TMwR/files/5441730/_main.pdf)

**Comment by topepo** [comment]
I appreciate the hard work but, as stated in #89, we won't be thinking much about a pdf until we are done. 

I would suspect that this might be brittle (i.e. new versions might break your code). Based on the last book that I wrote, we'll need to have a separate codebase for the pdf version due to the major changes in formatting, graphic devices, `\cite`/`index` commands, etc.
